create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    num_green_ml integer null default 0,
    gold integer null default 100,
    num_red_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    potion_sku text not null,
    name text null,
    price integer null default 30,
    quantity integer null default 0,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    constraint potion_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customer_information (
    id bigint generated by default as identity not null,
    name text not null,
    level integer null,
    class text null,
    constraint customer_information_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customer_cart (
    id bigint generated by default as identity not null,
    customer_id bigint null,
    payment text null,
    constraint customer_cart_pkey primary key (id),
    constraint customer_cart_customer_id_fkey foreign key (customer_id) references customer_information (id)
  ) tablespace pg_default;


  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id bigint not null,
    quantity integer null default 0,
    line_item_total integer null default 0,
    potion_id bigint null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references customer_cart (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inventory (id)
  ) tablespace pg_default;