create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    num_green_ml integer null default 0,
    gold integer null default 100,
    num_red_ml integer null default 0,
    num_blue_ml integer null default 0,
    num_dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_inventory (
    potion_id bigint generated by default as identity not null,
    potion_sku text not null,
    name text null,
    price integer null default 30,
    quantity integer null default 0,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml integer null default 0,
    constraint potion_inventory_pkey primary key (potion_id)
  ) tablespace pg_default;

create table
  public.customer_cart (
    cart_id bigint generated by default as identity not null,
    customer_name text not null,
    constraint customer_cart_pkey primary key (cart_id)
  ) tablespace pg_default;

create table
public.cart_items (
    cart_item_id bigint generated by default as identity not null,
    cart_id integer not null,
    potion_sku text null,
    quantity integer null default 0,
    line_item_total integer null default 0,
    constraint cart_items_pkey primary key (cart_item_id)
) tablespace pg_default;