create table
  public.gold_ledger (
    id bigint generated by default as identity not null,
    gold integer null,
    created_at timestamp with time zone not null default now(),
    constraint gold_ledger_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.ml_ledger (
    id bigint generated by default as identity not null,
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark_ml integer null,
    created_at timestamp with time zone not null default now(),
    constraint ml_ledger_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_ledger (
    id bigint generated by default as identity not null,
    potion_sku text null default 'NHpotions'::text,
    name text null default 'Apotion'::text,
    quantity integer null default 1,
    created_at timestamp with time zone not null default now(),
    price integer null default 30,
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark_ml integer null,
    constraint potion_ledger_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customer_information (
    id bigint generated by default as identity not null,
    name text not null,
    level integer null,
    class text null,
    constraint customer_information_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.customer_cart (
    id bigint generated by default as identity not null,
    customer_id bigint null,
    payment text null,
    constraint customer_cart_pkey primary key (id),
    constraint customer_cart_customer_id_fkey foreign key (customer_id) references customer_information (id)
  ) tablespace pg_default;


  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id bigint not null,
    quantity integer null default 0,
    line_item_total integer null default 0,
    potion_id bigint null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references customer_cart (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inventory (id)
  ) tablespace pg_default;